<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>SklaDinya_desktop_BL_component</RootNamespace>
    <AssemblyName>SklaDinya_desktop_BL_component</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Enums\" />
    <Folder Include="Models\" />
    <Folder Include="Forms\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Queries\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
